// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire gen -tags "netgo sqlite_fts5"
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"context"
	"github.com/google/wire"
	"github.com/hensi01/play-music/core"
	"github.com/hensi01/play-music/core/agents"
	"github.com/hensi01/play-music/core/artwork"
	"github.com/hensi01/play-music/core/external"
	"github.com/hensi01/play-music/core/ffmpeg"
	"github.com/hensi01/play-music/core/matcher"
	"github.com/hensi01/play-music/core/metrics"
	"github.com/hensi01/play-music/core/playlists"
	"github.com/hensi01/play-music/db"
	"github.com/hensi01/play-music/model"
	"github.com/hensi01/play-music/persistence"
	"github.com/hensi01/play-music/scanner"
	"github.com/hensi01/play-music/server"
	"github.com/hensi01/play-music/server/events"
)

import (
	_ "github.com/hensi01/play-music/adapters/gotaglib"
	_ "github.com/hensi01/play-music/core/storage/local"
	_ "github.com/hensi01/play-music/core/storage/s3"
)

// Injectors from wire_injectors.go:

func CreateDataStore() model.DataStore {
	sqlDB := db.Db()
	dataStore := persistence.New(sqlDB)
	return dataStore
}

func CreateServer() *server.Server {
	sqlDB := db.Db()
	dataStore := persistence.New(sqlDB)
	broker := events.GetBroker()
	serverServer := server.New(dataStore, broker)
	return serverServer
}

func CreateScanner(ctx context.Context) model.Scanner {
	sqlDB := db.Db()
	dataStore := persistence.New(sqlDB)
	fileCache := artwork.GetImageCache()
	fFmpeg := ffmpeg.New()
	agentsAgents := agents.GetAgents(dataStore)
	matcherMatcher := matcher.New(dataStore)
	provider := external.NewProvider(dataStore, agentsAgents, matcherMatcher)
	artworkArtwork := artwork.NewArtwork(dataStore, fileCache, fFmpeg, provider)
	cacheWarmer := artwork.NewCacheWarmer(artworkArtwork, fileCache)
	broker := events.GetBroker()
	imageUploadService := core.NewImageUploadService()
	playlistsPlaylists := playlists.NewPlaylists(dataStore, imageUploadService)
	metricsMetrics := metrics.GetPrometheusInstance(dataStore)
	modelScanner := scanner.New(ctx, dataStore, cacheWarmer, broker, playlistsPlaylists, metricsMetrics)
	return modelScanner
}

func CreateScanWatcher(ctx context.Context) scanner.Watcher {
	sqlDB := db.Db()
	dataStore := persistence.New(sqlDB)
	fileCache := artwork.GetImageCache()
	fFmpeg := ffmpeg.New()
	agentsAgents := agents.GetAgents(dataStore)
	matcherMatcher := matcher.New(dataStore)
	provider := external.NewProvider(dataStore, agentsAgents, matcherMatcher)
	artworkArtwork := artwork.NewArtwork(dataStore, fileCache, fFmpeg, provider)
	cacheWarmer := artwork.NewCacheWarmer(artworkArtwork, fileCache)
	broker := events.GetBroker()
	imageUploadService := core.NewImageUploadService()
	playlistsPlaylists := playlists.NewPlaylists(dataStore, imageUploadService)
	metricsMetrics := metrics.GetPrometheusInstance(dataStore)
	modelScanner := scanner.New(ctx, dataStore, cacheWarmer, broker, playlistsPlaylists, metricsMetrics)
	watcher := scanner.GetWatcher(dataStore, modelScanner)
	return watcher
}

// wire_injectors.go:

var allProviders = wire.NewSet(core.Set, artwork.Set, server.New, persistence.New, events.GetBroker, scanner.New, scanner.GetWatcher, metrics.GetPrometheusInstance, db.Db, wire.Bind(new(core.Watcher), new(scanner.Watcher)))
